name: Build and deploy .NET application to container app weatherforecast-app-202407231837
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: weatherforecastsy
  CONTAINER_APP_NAME: weatherforecast-app-202407231837
  CONTAINER_APP_RESOURCE_GROUP_NAME: httpexamplebyyakhin1916
  CONTAINER_REGISTRY_LOGIN_SERVER: weatherforecast20240723184052.azurecr.io
  DOCKER_FILE_PATH: WeatherForecast/Dockerfile
  PROJECT_NAME_FOR_DOCKER: weatherforecast
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.WeatherForecast20240723184052_USERNAME_DA4B }}
        password: ${{ secrets.WeatherForecast20240723184052_PASSWORD_DA4B }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.weatherforecast_app_202407231837_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.WeatherForecast20240723184052_USERNAME_DA4B }} --password ${{ secrets.WeatherForecast20240723184052_PASSWORD_DA4B }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
